import { useMemo, useState } from 'react';
import { Download, FileSearch, Filter, ShieldCheck } from 'lucide-react';
import { Badge, Button, toast } from '@de/web-ui';
import { useApiMutation, useApiQuery } from '@/services/query';

type AuditRow = { id: string; time: string; actor: string; action: string; target: string; result: 'success' | 'failed'; workspaceId?: string; correlationId: string };

export default function AuditCenter() {
  const [query, setQuery] = useState('');
  const audit = useApiQuery<AuditRow[]>(['audit-center'], '/api/audit-center', undefined, { refetchInterval: 15_000 });
  const exportEvidence = useApiMutation<{ filename: string; recordCount: number; masked: boolean }, Record<string, never>>('/api/audit-center/export', { onSuccess: (data) => toast.success(`已生成 ${data.filename}，共 ${data.recordCount} 条脱敏记录`), onError: (error: any) => toast.error(error?.message ?? '导出失败') });
  const rows = useMemo(() => (audit.data ?? []).filter((item) => `${item.actor} ${item.action} ${item.target} ${item.correlationId}`.toLowerCase().includes(query.toLowerCase())), [audit.data, query]);
  return <div className="mx-auto min-h-full max-w-[1480px] p-3 sm:p-4 lg:p-5"><header className="rounded-lg border border-[var(--border)] bg-[var(--bg)] px-4 py-4 sm:px-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-base font-semibold"><FileSearch className="h-4 w-4 text-[var(--brand)]" />审计中心</h1><p className="mt-1 text-xs text-[var(--text-muted)]">只读追溯工作区内的授权、发布、策略与运行治理事件。</p></div><Button size="sm" variant="secondary" loading={exportEvidence.isPending} onClick={() => exportEvidence.mutate({})}><Download className="h-3.5 w-3.5" />导出脱敏证据包</Button></div><div className="mt-4 flex h-9 items-center gap-2 rounded-md border border-[var(--border)] bg-[var(--bg-elevated)] px-3"><Filter className="h-3.5 w-3.5 text-[var(--text-muted)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="按操作人、资源、关联 ID 搜索" className="min-w-0 flex-1 bg-transparent text-xs outline-none placeholder:text-[var(--text-muted)]" /></div></header><section className="mt-3 overflow-hidden rounded-lg border border-[var(--border)] bg-[var(--bg)]"><div className="flex items-center justify-between border-b border-[var(--border)] px-4 py-3"><div className="text-sm font-semibold">审计事件</div><span className="text-[11px] text-[var(--text-muted)]">{rows.length} 条授权范围内记录</span></div>{audit.isLoading ? <div className="p-10 text-center text-xs text-[var(--text-muted)]">正在读取审计证据…</div> : <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-xs"><thead className="bg-[var(--bg-elevated)] text-[var(--text-muted)]"><tr><th className="px-4 py-2.5 font-medium">时间</th><th className="px-4 py-2.5 font-medium">操作人</th><th className="px-4 py-2.5 font-medium">事件</th><th className="px-4 py-2.5 font-medium">目标</th><th className="px-4 py-2.5 font-medium">结果</th><th className="px-4 py-2.5 font-medium">关联 ID</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id} className="border-t border-[var(--border)]"><td className="whitespace-nowrap px-4 py-3 text-[var(--text-muted)]">{new Date(item.time).toLocaleString('zh-CN')}</td><td className="px-4 py-3 font-medium">{item.actor}</td><td className="px-4 py-3">{item.action}</td><td className="px-4 py-3 text-[var(--text-secondary)]">{item.target}</td><td className="px-4 py-3"><Badge tone={item.result === 'success' ? 'success' : 'error'}>{item.result === 'success' ? '成功' : '失败'}</Badge></td><td className="px-4 py-3 font-mono text-[10px] text-[var(--text-muted)]">{item.correlationId}</td></tr>)}</tbody></table></div>}</section><p className="mt-3 flex items-center gap-1.5 text-[11px] text-[var(--text-muted)]"><ShieldCheck className="h-3.5 w-3.5 text-[var(--success)]" />审计视图只读；证据导出默认脱敏并记录导出行为。</p></div>;
}
